# Generated by Django 5.0.6 on 2024-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=55)),
                ('age', models.IntegerField()),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
